apiVersion: v2
name: todo-chatbot
description: A cloud-native Todo Chatbot application with frontend and backend
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - todo
  - chatbot
  - ai
  - fullstack
home: https://github.com/example/todo-chatbot
sources:
  - https://github.com/example/todo-chatbot
maintainers:
  - name: Todo Chatbot Team
    email: team@example.com