apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: recurring-tasks-cron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 1m"  # Check every minute for recurring tasks